import { STAGE_NAMES, type StageName } from "@createverse/design-tokens";
import { renderButton } from "./Button.ts";
import {
  renderCard,
  renderChip,
  renderDialog,
  renderHintButton,
  renderParentGate,
  renderPortfolioCard,
  renderSafetyNotice,
  renderStepProgress,
  renderTabs,
} from "./components.ts";
import { escapeHtml } from "./escape.ts";
import { ICON_NAMES, renderIcon, type IconName } from "./Icon.ts";
import { fullCss } from "./styles.ts";

/**
 * Preview page (P0-04, DESIGN_SYSTEM.md §10): renders every component in
 * every stage preset, in English and Traditional Chinese.
 *
 * Components are rendered without a `stage` prop — each gallery block sets
 * `data-stage` on its root, exactly like the app root does (§10), so the page
 * also demonstrates live preset switching.
 */

type Lang = "en" | "zh-Hant";

export const LANGS: readonly Lang[] = ["en", "zh-Hant"];

interface Strings {
  readonly pageTitle: string;
  readonly pageTag: string;
  readonly presetLabel: string;
  readonly langLabel: string;
  readonly navLabel: string;
  readonly liveHeading: string;
  readonly liveNote: string;
  readonly galleryHeading: string;
  readonly galleryNote: string;
  readonly footer: string;
  readonly stages: Readonly<Record<StageName, string>>;
  readonly buttonPrimary: string;
  readonly buttonSecondary: string;
  readonly buttonDisabled: string;
  readonly buttonLoading: string;
  readonly cardTitle: string;
  readonly cardBody: string;
  readonly chip: string;
  readonly chipSelected: string;
  readonly tabs: readonly [string, string, string];
  readonly dialogTitle: string;
  readonly dialogBody: string;
  readonly stepProgress: string;
  readonly hint: string;
  readonly hintAria: string;
  readonly portfolioTitle: string;
  readonly portfolioDetail: string;
  readonly portfolioDate: string;
  readonly parentGateReason: string;
  readonly parentGateAction: string;
  readonly severityInfo: string;
  readonly severityWarning: string;
  readonly safetyInfo: string;
  readonly safetyInfoNext: string;
  readonly safetyWarning: string;
  readonly safetyWarningNext: string;
  readonly icons: Readonly<Record<IconName, string>>;
  readonly captions: Readonly<Record<string, string>>;
}

const EN: Strings = {
  pageTitle: "Createverse UI",
  pageTag: "Component preview · P0-04",
  presetLabel: "Preset",
  langLabel: "Language",
  navLabel: "Page sections",
  liveHeading: "Live demo",
  liveNote: "Switch the preset and language in the header — this block follows your selection.",
  galleryHeading: "All presets",
  galleryNote: "Every component in each age preset. Use the language switch to view English or 繁體中文.",
  footer: "Generated by pnpm ui:preview — do not edit by hand.",
  stages: {
    junior: "Junior (3–5)",
    explorer: "Explorer (6–8)",
    maker: "Maker (8–10)",
    parent: "Parent",
  },
  buttonPrimary: "Start",
  buttonSecondary: "Try again",
  buttonDisabled: "Continue",
  buttonLoading: "Saving…",
  cardTitle: "Build a Bridge",
  cardBody: "Put the planks together so the toy car can cross.",
  chip: "Wood",
  chipSelected: "Stone",
  tabs: ["Story", "Learn", "Create"],
  dialogTitle: "Save your work?",
  dialogBody: "We can keep this and take a break.",
  stepProgress: "Step 2 of 4",
  hint: "Hint",
  hintAria: "Get a hint",
  portfolioTitle: "My bridge",
  portfolioDetail: "It held for 8 seconds.",
  portfolioDate: "2026-10-06",
  parentGateReason: "Changing this setting needs a grown-up.",
  parentGateAction: "Confirm with passkey",
  severityInfo: "Information",
  severityWarning: "Warning",
  safetyInfo: "This activity uses small parts.",
  safetyInfoNext: "Ask a grown-up to join you.",
  safetyWarning: "This activity never uses real tools.",
  safetyWarningNext: "Build only with the pieces on screen.",    icons: {
    home: "Home",
    explore: "Explore",
    create: "Create",
    projects: "Projects",
    me: "Me",
    hint: "Hint",
    speaker: "Read aloud",
    play: "Play",
    undo: "Undo",
    redo: "Redo",
    lock: "Locked",
    close: "Close",
    check: "Done",
    warning: "Warning",
    info: "Information",
    arrowLeft: "Back",
    book: "Story",
  },    captions: {
    buttonPrimary: "Button — primary",
    buttonSecondary: "Button — secondary",
    buttonDisabled: "Button — disabled",
    buttonLoading: "Button — loading",
    icons: "Icons — each with an accessible name",
    card: "Card",
    chip: "Chip (normal and selected)",
    tabs: "Tabs",
    dialog: "Dialog",
    stepProgress: "Step progress",
    hint: "Mentor hint (icon + label, no character)",
    portfolio: "Portfolio card",
    parentGate: "Parent gate",
    safetyInfo: "Safety notice — info",
    safetyWarning: "Safety notice — warning",
  },
};

const ZH: Strings = {
  pageTitle: "Createverse 介面",
  pageTag: "元件預覽 · P0-04",
  presetLabel: "階段",
  langLabel: "語言",
  navLabel: "頁面章節",
  liveHeading: "即時示範",
  liveNote: "在頁首切換階段與語言，此區塊會跟著更新。",
  galleryHeading: "所有階段",
  galleryNote: "每個階段的所有元件。可用語言切換查看英文或繁體中文。",
  footer: "由 pnpm ui:preview 產生 — 請勿手動編輯。",
  stages: {
    junior: "幼兒（3–5 歲）",
    explorer: "探索者（6–8 歲）",
    maker: "創作者（8–10 歲）",
    parent: "家長",
  },
  buttonPrimary: "開始",
  buttonSecondary: "再試一次",
  buttonDisabled: "繼續",
  buttonLoading: "保存中…",
  cardTitle: "蓋一座橋",
  cardBody: "把木板拼起來，讓玩具車順利通過。",
  chip: "木頭",
  chipSelected: "石頭",
  tabs: ["故事", "學習", "創作"],
  dialogTitle: "要保存作品嗎？",
  dialogBody: "我們可以先保存作品，休息一下。",
  stepProgress: "第 2 步，共 4 步",
  hint: "提示",
  hintAria: "取得提示",
  portfolioTitle: "我的橋",
  portfolioDetail: "它撐住了 8 秒。",
  portfolioDate: "2026-10-06",
  parentGateReason: "變更這個設定需要家長確認。",
  parentGateAction: "用通行密鑰確認",
  severityInfo: "資訊",
  severityWarning: "注意",
  safetyInfo: "這個活動會用到小零件。",
  safetyInfoNext: "請家長陪你一起進行。",
  safetyWarning: "這個活動不會用到真正的工具。",
  safetyWarningNext: "只用畫面上的積木來搭建。",    icons: {
    home: "首頁",
    explore: "探索",
    create: "創作",
    projects: "作品",
    me: "我",
    hint: "提示",
    speaker: "朗讀",
    play: "播放",
    undo: "復原",
    redo: "重做",
    lock: "已鎖定",
    close: "關閉",
    check: "完成",
    warning: "注意",
    info: "資訊",
    arrowLeft: "返回",
    book: "故事",
  },
  captions: {
    buttonPrimary: "按鈕 — 主要",
    buttonSecondary: "按鈕 — 次要",
    buttonDisabled: "按鈕 — 停用",
    buttonLoading: "按鈕 — 載入中",
    icons: "圖示 — 每個都有無障礙名稱",
    card: "卡片",
    chip: "標籤（一般與已選取）",
    tabs: "分頁",
    dialog: "對話框",
    stepProgress: "步驟進度",
    hint: "導師提示（圖示＋文字，不扮角色）",
    portfolio: "作品卡",
    parentGate: "家長確認",
    safetyInfo: "安全提示 — 資訊",
    safetyWarning: "安全提示 — 注意",
  },
};

const STRINGS: Readonly<Record<Lang, Strings>> = { en: EN, "zh-Hant": ZH };

function figure(caption: string, body: string): string {
  return `<figure class="pv-field"><figcaption>${escapeHtml(caption)}</figcaption>${body}</figure>`;
}

function componentColumn(lang: Lang): string {
  const s = STRINGS[lang];
  const icons = ICON_NAMES.map(
    (name) =>
      `<span class="pv-icon-demo">${renderIcon({ name, label: s.icons[name] })}` +
      `<span>${escapeHtml(s.icons[name])}</span></span>`,
  ).join("");

  return [
    figure(s.captions["buttonPrimary"] ?? "", renderButton({ label: s.buttonPrimary })),
    figure(s.captions["buttonSecondary"] ?? "", renderButton({ label: s.buttonSecondary, variant: "secondary" })),
    figure(s.captions["buttonDisabled"] ?? "", renderButton({ label: s.buttonDisabled, disabled: true })),
    figure(s.captions["buttonLoading"] ?? "", renderButton({ label: s.buttonLoading, loading: true })),
    figure(s.captions["icons"] ?? "", `<div class="pv-row">${icons}</div>`),
    figure(s.captions["card"] ?? "", renderCard({ label: s.cardTitle, body: s.cardBody })),
    figure(
      s.captions["chip"] ?? "",
      `<div class="pv-row">` +
        renderChip({ label: s.chip }) +
        renderChip({ label: s.chipSelected, selected: true }) +
        `</div>`,
    ),
    figure(s.captions["tabs"] ?? "", renderTabs({ tabs: s.tabs, active: 1 })),
    figure(s.captions["dialog"] ?? "", renderDialog({ label: s.dialogTitle, body: s.dialogBody, open: true })),
    figure(s.captions["stepProgress"] ?? "", renderStepProgress({ current: 2, total: 4, label: s.stepProgress })),
    figure(
      s.captions["hint"] ?? "",
      renderHintButton({ level: 1, label: s.hint, ariaLabel: s.hintAria }),
    ),
    figure(
      s.captions["portfolio"] ?? "",
      renderPortfolioCard({ label: s.portfolioTitle, detail: s.portfolioDetail, date: s.portfolioDate }),
    ),
    figure(
      s.captions["parentGate"] ?? "",
      renderParentGate({ reason: s.parentGateReason, actionLabel: s.parentGateAction }),
    ),
    figure(
      s.captions["safetyInfo"] ?? "",
      renderSafetyNotice({
        severity: "info",
        message: s.safetyInfo,
        nextStep: s.safetyInfoNext,
        severityLabel: s.severityInfo,
      }),
    ),
    figure(
      s.captions["safetyWarning"] ?? "",
      renderSafetyNotice({
        severity: "warning",
        message: s.safetyWarning,
        nextStep: s.safetyWarningNext,
        severityLabel: s.severityWarning,
      }),
    ),
  ].join("\n");
}

/** English-first label pair: English visible by default, Chinese toggled by the language switch. */
function t(en: string, zh: string): string {
  return (
    `<span lang="en" data-lang-block="en">${escapeHtml(en)}</span>` +
    `<span lang="zh-Hant" data-lang-block="zh-Hant" hidden>${escapeHtml(zh)}</span>`
  );
}

function stageHeading(stage: StageName): string {
  return t(EN.stages[stage], ZH.stages[stage]);
}

const PREVIEW_CSS = `
[hidden] {
  display: none !important;
}
*,
*::before,
*::after {
  box-sizing: border-box;
}
body.pv-body {
  margin: 0;
  background: var(--cv-color-bg);
  color: var(--cv-color-text);
  font-family: var(--cv-font);
  font-size: var(--cv-font-size-body);
  line-height: var(--cv-line-height);
}
.pv-header {
  position: sticky;
  top: 0;
  z-index: 10;
  background: var(--cv-color-surface);
  border-bottom: 2px solid var(--cv-color-border);
  box-shadow: var(--cv-elevation-1);
}
.pv-header-inner {
  display: flex;
  flex-wrap: wrap;
  gap: var(--cv-space-4);
  align-items: center;
  justify-content: space-between;
  max-width: 72rem;
  margin: 0 auto;
  padding: var(--cv-space-4) var(--cv-space-5);
}
.pv-brand h1 {
  margin: 0;
  font-size: var(--cv-font-size-title);
  line-height: 1.2;
}
.pv-tag {
  margin: var(--cv-space-1) 0 0;
  color: var(--cv-color-text-muted);
  font-size: var(--cv-font-size-small);
}
.pv-controls {
  display: flex;
  flex-wrap: wrap;
  gap: var(--cv-space-5);
}
.pv-control {
  display: grid;
  gap: var(--cv-space-1);
}
.pv-control-label {
  color: var(--cv-color-text-muted);
  font-size: var(--cv-font-size-small);
  font-weight: 600;
  letter-spacing: 0.06em;
  text-transform: uppercase;
}
.pv-segment {
  display: flex;
  flex-wrap: wrap;
  gap: var(--cv-space-2);
}
.pv-segment button {
  min-height: var(--cv-touch-target);
  padding: var(--cv-space-2) var(--cv-space-4);
  border: 2px solid var(--cv-color-border);
  border-radius: var(--cv-radius-full);
  background: var(--cv-color-surface-alt);
  color: var(--cv-color-text);
  font-family: var(--cv-font);
  font-size: var(--cv-font-size-small);
  font-weight: 600;
  cursor: pointer;
}
.pv-segment button:hover {
  border-color: var(--cv-color-text);
}
.pv-segment button[aria-pressed="true"] {
  background: var(--cv-color-primary);
  border-color: var(--cv-color-primary);
  color: var(--cv-color-on-primary);
  text-decoration: underline;
  text-underline-offset: 0.25em;
}
.pv-nav {
  display: flex;
  flex-wrap: wrap;
  gap: var(--cv-space-2);
  max-width: 72rem;
  margin: 0 auto;
  padding: var(--cv-space-4) var(--cv-space-5) 0;
}
.pv-nav a {
  display: inline-flex;
  align-items: center;
  min-height: var(--cv-touch-target);
  padding: var(--cv-space-2) var(--cv-space-4);
  border-radius: var(--cv-radius-full);
  color: var(--cv-color-text);
  font-size: var(--cv-font-size-small);
  font-weight: 600;
  text-decoration: none;
}
.pv-nav a:hover {
  background: var(--cv-color-surface-alt);
}
.pv-main {
  max-width: 72rem;
  margin: 0 auto;
  padding: var(--cv-space-5);
}
.pv-gallery > .pv-section-head {
  margin-bottom: var(--cv-space-5);
}
.pv-block {
  margin-bottom: var(--cv-space-6);
  padding: var(--cv-space-5);
  border: 2px solid var(--cv-color-border);
  border-radius: var(--cv-component-radius, var(--cv-radius-lg));
  background: var(--cv-color-surface);
  box-shadow: var(--cv-elevation-1);
  scroll-margin-top: calc(var(--cv-touch-target) + var(--cv-space-8) + var(--cv-space-4));
}
.pv-section-head {
  display: grid;
  gap: var(--cv-space-2);
  margin-bottom: var(--cv-space-5);
}
.pv-section-head h2 {
  margin: 0;
  font-size: var(--cv-font-size-title);
}
.pv-note {
  max-width: 65ch;
  margin: 0;
  color: var(--cv-color-text-muted);
  font-size: var(--cv-font-size-small);
}
.pv-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(16rem, 1fr));
  gap: var(--cv-space-4);
}
.pv-col {
  display: contents;
}
.pv-field {
  display: grid;
  gap: var(--cv-space-2);
  align-content: start;
  margin: 0;
  padding: var(--cv-space-4);
  border: 2px solid var(--cv-color-border);
  border-radius: var(--cv-component-radius, var(--cv-radius-lg));
  background: var(--cv-color-surface-alt);
}
.pv-field figcaption {
  color: var(--cv-color-text-muted);
  font-size: var(--cv-font-size-small);
  font-weight: 600;
  letter-spacing: 0.04em;
  text-transform: uppercase;
}
.pv-row {
  display: flex;
  flex-wrap: wrap;
  gap: var(--cv-space-3);
  align-items: center;
}
.pv-icon-demo {
  display: inline-flex;
  align-items: center;
  gap: var(--cv-space-1);
  font-size: var(--cv-font-size-small);
}
.pv-footer {
  max-width: 72rem;
  margin: 0 auto;
  padding: var(--cv-space-5);
  border-top: 2px solid var(--cv-color-border);
  color: var(--cv-color-text-muted);
  font-size: var(--cv-font-size-small);
}
@media (max-width: 40rem) {
  .pv-header-inner {
    align-items: flex-start;
    flex-direction: column;
  }
}
`;

const PREVIEW_SCRIPT = `
const stageButtons = Array.from(document.querySelectorAll("[data-set-stage]"));
stageButtons.forEach((button) => {
  button.addEventListener("click", () => {
    const stage = button.getAttribute("data-set-stage");
    document.getElementById("pv-live").setAttribute("data-stage", stage);
    document.body.setAttribute("data-stage", stage);
    stageButtons.forEach((other) =>
      other.setAttribute("aria-pressed", String(other === button)),
    );
  });
});
const langButtons = Array.from(document.querySelectorAll("[data-set-lang]"));
langButtons.forEach((button) => {
  button.addEventListener("click", () => {
    const lang = button.getAttribute("data-set-lang");
    document.querySelectorAll("[data-lang-block]").forEach((block) => {
      block.hidden = block.getAttribute("data-lang-block") !== lang;
    });
    document.documentElement.lang = lang;
    document.getElementById("pv-live").setAttribute("lang", lang);
    langButtons.forEach((other) =>
      other.setAttribute("aria-pressed", String(other === button)),
    );
  });
});
`;

function galleryBlock(stage: StageName): string {
  return (
    `<section class="pv-block" id="pv-${stage}" data-stage="${stage}" aria-labelledby="pv-${stage}-h">` +
    `<div class="pv-section-head"><h2 id="pv-${stage}-h">${stageHeading(stage)}</h2></div>` +
    `<div class="pv-grid">` +
    `<div class="pv-col" lang="en" data-lang-block="en">${componentColumn("en")}</div>` +
    `<div class="pv-col" lang="zh-Hant" data-lang-block="zh-Hant" hidden>${componentColumn("zh-Hant")}</div>` +
    `</div></section>`
  );
}

/** Build the complete preview page as a standalone HTML document. */
export function renderPreviewPage(): string {
  const stageButtons = STAGE_NAMES.map(
    (stage) =>
      `<button type="button" data-set-stage="${stage}" aria-pressed="${stage === "junior"}">` +
      t(EN.stages[stage], ZH.stages[stage]) +
      `</button>`,
  ).join("");

  const navLinks =
    `<a href="#pv-live">${t(EN.liveHeading, ZH.liveHeading)}</a>` +
    STAGE_NAMES.map(
      (stage) => `<a href="#pv-${stage}">${t(EN.stages[stage], ZH.stages[stage])}</a>`,
    ).join("");

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(EN.pageTitle)}</title>
<style>
${fullCss()}
${PREVIEW_CSS}
</style>
</head>
<body class="pv-body" data-stage="junior">
<header class="pv-header">
<div class="pv-header-inner">
<div class="pv-brand">
<h1>${t(EN.pageTitle, ZH.pageTitle)}</h1>
<p class="pv-tag">${t(EN.pageTag, ZH.pageTag)}</p>
</div>
<div class="pv-controls">
<div class="pv-control">
<span class="pv-control-label" id="pv-preset-label">${t(EN.presetLabel, ZH.presetLabel)}</span>
<div class="pv-segment" role="group" aria-labelledby="pv-preset-label">${stageButtons}</div>
</div>
<div class="pv-control">
<span class="pv-control-label" id="pv-lang-label">${t(EN.langLabel, ZH.langLabel)}</span>
<div class="pv-segment" role="group" aria-labelledby="pv-lang-label">
<button type="button" data-set-lang="en" aria-pressed="true">English</button>
<button type="button" data-set-lang="zh-Hant" aria-pressed="false">繁體中文</button>
</div>
</div>
</div>
</div>
</header>
<nav class="pv-nav" aria-label="${escapeHtml(EN.navLabel)}">${navLinks}</nav>
<main class="pv-main">
<section class="pv-block" id="pv-live" data-stage="junior" lang="en" aria-labelledby="pv-live-h">
<div class="pv-section-head">
<h2 id="pv-live-h">${t(EN.liveHeading, ZH.liveHeading)}</h2>
<p class="pv-note">${t(EN.liveNote, ZH.liveNote)}</p>
</div>
<div class="pv-grid" lang="en" data-lang-block="en">${componentColumn("en")}</div>
<div class="pv-grid" lang="zh-Hant" data-lang-block="zh-Hant" hidden>${componentColumn("zh-Hant")}</div>
</section>
<section class="pv-gallery" aria-labelledby="pv-gallery-h">
<div class="pv-section-head">
<h2 id="pv-gallery-h">${t(EN.galleryHeading, ZH.galleryHeading)}</h2>
<p class="pv-note">${t(EN.galleryNote, ZH.galleryNote)}</p>
</div>
${STAGE_NAMES.map(galleryBlock).join("\n")}
</section>
</main>
<footer class="pv-footer">${t(EN.footer, ZH.footer)}</footer>
<script>
${PREVIEW_SCRIPT}
</script>
</body>
</html>
`;
}
